import {z} from 'zod';
import {vimeoEmbed} from '@/lib/video';
import {demoAlbum} from '@/lib/demo';
import {checkOrigin,database,failure,HttpError,privateHeaders,requireAdmin} from '@/lib/server';
import type {Album,Photo} from '@/lib/types';
const schema=z.object({title:z.string().trim().min(1).max(100),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(90),description:z.string().max(1500),category:z.string().trim().min(1).max(60),video:z.string().max(500),photos:z.array(z.object({id:z.string().max(80),caption:z.string().max(240)})).max(200),highlights:z.array(z.string().max(80)).max(5),cover:z.string().max(80),published:z.boolean(),order:z.number().int().min(0).max(999),version:z.number().int().min(1)});
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){try{await requireAdmin();checkOrigin(request);if(Number(request.headers.get('content-length')||0)>150000)throw new HttpError(413,'Este trabalho ultrapassou o limite de tamanho.');const data=schema.parse(await request.json());const {id}=await params;const db=database();const row=await db.prepare('SELECT data,version FROM albums WHERE id=?').bind(id).first<{data:string;version:number}>();if(!row)throw new HttpError(404,'Trabalho não encontrado.');if(row.version!==data.version)throw new HttpError(409,'Este trabalho foi atualizado em outra aba. Recarregue o painel antes de continuar.');const old:Album=JSON.parse(row.data);
 if(data.video&&!vimeoEmbed(data.video))throw new HttpError(400,'Use o link completo de compartilhamento ou do player do Vimeo.');
 const stored=await db.prepare('SELECT id FROM assets WHERE album_id=?').bind(id).all<{id:string}>();const allowed=new Set(stored.results.map(p=>p.id));const demoIds=new Map((old.demo?demoAlbum.photos:[]).map(p=>[p.id,p]));const ids=new Set(data.photos.map(p=>p.id));if(ids.size!==data.photos.length||data.photos.some(p=>!allowed.has(p.id)&&!demoIds.has(p.id)))throw new HttpError(400,'Há fotos inválidas na seleção. Atualize a página.');
 if(new Set(data.highlights).size!==data.highlights.length||data.highlights.some(p=>!ids.has(p))||(data.cover&&!ids.has(data.cover)))throw new HttpError(400,'Escolha destaques e capa entre as fotos deste trabalho.');
 if(data.published&&(!data.photos.length||!data.highlights.length||!data.cover||!data.highlights.includes(data.cover)))throw new HttpError(400,'Para publicar, escolha ao menos uma foto, uma capa e até cinco destaques. A capa deve ser um destaque.');
 const duplicate=await db.prepare('SELECT id FROM albums WHERE slug=? AND id!=?').bind(data.slug,id).first();if(duplicate)throw new HttpError(409,'Este endereço já está em uso. Escolha outro.');
 const photos:Photo[]=data.photos.map(p=>{const demo=demoIds.get(p.id);return demo?{...demo,caption:p.caption}:{...p,url:`/api/photos/${p.id}`,thumb:`/api/photos/${p.id}?size=thumb`}});const highlights=data.cover&&data.highlights.includes(data.cover)?[data.cover,...data.highlights.filter(p=>p!==data.cover)]:data.highlights;
 const next:Album={...old,...data,photos,highlights,version:row.version+1};const result=await db.prepare('UPDATE albums SET slug=?,data=?,published=?,sort_order=?,version=version+1 WHERE id=? AND version=?').bind(next.slug,JSON.stringify(next),next.published?1:0,next.order,id,row.version).run();if(!result.meta.changes)throw new HttpError(409,'Outra aba salvou antes. Recarregue para ver a versão atual.');return Response.json(next,{headers:privateHeaders});
 }catch(e){return failure(e instanceof z.ZodError?new HttpError(400,'Confira os campos: título, endereço, fotos e ordem devem ser válidos.'):e)}}
