"use client";
import { useEffect,useRef,useState } from 'react';
import { ArrowDown,ArrowLeft,ArrowUpRight,ChevronLeft,ChevronRight,Monitor,Moon,Play,Sun } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import type { Album,Photo,Profile } from '@/lib/types';
import { vimeoEmbed } from '@/lib/video';
export function SiteHeader({name,logo,logoDark}:Pick<Profile,'name'|'logo'|'logoDark'>){
 const [mode,setMode]=useState('system');useEffect(()=>{try{setMode(localStorage.getItem('portfolio-theme')||'system')}catch{}},[]);
 function change(){const next=mode==='system'?'dark':mode==='dark'?'light':'system';setMode(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('portfolio-theme',next)}catch{}}
 return <header className="site-header"><a href="/" className="wordmark" aria-label={`${name} — início`}>{logo||logoDark?<><img className="brand-logo logo-light" src={logo||logoDark} alt={name}/><img className="brand-logo logo-dark" src={logoDark||logo} alt={name}/></>:<>{name}<span>Histórias em imagens</span></>}</a><nav><a href="/#historias">Portfólio</a><button className="theme-button" onClick={change} aria-label={`Tema ${mode==='system'?'automático':mode==='dark'?'escuro':'claro'}. Alternar tema`} title="Alternar: automático, escuro, claro">{mode==='system'?<Monitor size={18}/>:mode==='dark'?<Moon size={18}/>:<Sun size={18}/>}</button></nav></header>
}
export function SiteFooter({name}:{name:string}){return <footer className="site-footer"><span>{name}<span className="muted">© {new Date().getFullYear()}</span></span><a href="/admin">Área do fotógrafo <ArrowUpRight size={14}/></a></footer>}
function Motion(){useEffect(()=>{if(!('IntersectionObserver' in window))return;const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return null}
export function PhotoViewer({photos,index,onClose,onIndex}:{photos:Photo[];index:number;onClose:()=>void;onIndex:(n:number)=>void}){
 const touch=useRef<number|null>(null);const p=photos[index];function move(n:number){onIndex((index+n+photos.length)%photos.length)}
 useEffect(()=>{if(index<0)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft'){e.preventDefault();onIndex((index-1+photos.length)%photos.length)}if(e.key==='ArrowRight'){e.preventDefault();onIndex((index+1)%photos.length)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,photos.length,onIndex]);
 return <Dialog open={index>=0} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="photo-dialog" aria-describedby="photo-description"><DialogTitle className="sr-only">{p?.caption||'Fotografia ampliada'}</DialogTitle><DialogDescription id="photo-description" className="sr-only">Use as setas para navegar e Escape para fechar.</DialogDescription>{p&&<><div className="photo-stage" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current!==null){const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>50)move(d>0?-1:1);touch.current=null}}}><img key={p.id} src={p.url} alt={p.caption} className="full-photo"/><button className="viewer-prev" onClick={()=>move(-1)} aria-label="Foto anterior"><ChevronLeft/></button><button className="viewer-next" onClick={()=>move(1)} aria-label="Próxima foto"><ChevronRight/></button></div><div className="photo-caption"><span>{p.caption}{p.credit&&<> · <a href={p.source} target="_blank" rel="noreferrer">{p.credit} / Unsplash</a></>}</span><span>{String(index+1).padStart(2,'0')} / {String(photos.length).padStart(2,'0')}</span></div></>}</DialogContent></Dialog>
}
export function Film({album}:{album:Album}){const [open,setOpen]=useState(false);const embed=vimeoEmbed(album.video);if(!embed)return null;return <><button className="text-link" onClick={()=>setOpen(true)}><Play size={15}/> Assistir ao filme</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="film-dialog"><DialogTitle>{album.title} — o filme</DialogTitle><DialogDescription className="sr-only">Filme hospedado no Vimeo.</DialogDescription>{open&&<iframe src={embed} title={`Filme: ${album.title}`} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>}</DialogContent></Dialog></>}
export function Portfolio({albums,profile}:{albums:Album[];profile:Profile}){
 const [selected,setSelected]=useState<{photos:Photo[];index:number}>({photos:[],index:-1});
 return <><SiteHeader {...profile}/><main><section className="intro"><div className="eyebrow"><span className="fine-line"/> O que fica</div><h1>Histórias que<br/>a gente <em>sente.</em></h1><div className="intro-bottom"><p>{profile.introduction}</p><a href="#historias" className="down-link"><span>Explore as histórias</span><ArrowDown size={19}/></a></div></section><section id="historias" className="stories"><div className="section-line"><span>Histórias selecionadas</span><span>{String(albums.length).padStart(2,'0')}</span></div>{albums.map((a,n)=>{const chosen=a.highlights.map(id=>a.photos.find(p=>p.id===id)).filter((p):p is Photo=>!!p);return <article className="story reveal" key={a.id}><div className="story-heading"><div><div className="eyebrow">{String(n+1).padStart(2,'0')} / {a.category}{a.demo&&<span className="demo-badge">Demonstração</span>}</div><h2><a href={`/galeria/${a.slug}`} target="_blank" rel="noopener noreferrer">{a.title}</a></h2></div><div className="story-links"><Film album={a}/><a className="text-link" href={`/galeria/${a.slug}`} target="_blank" rel="noopener noreferrer">Ver galeria completa <ArrowUpRight size={17}/></a></div></div><div className={`editorial-grid count-${Math.min(chosen.length,5)}`}>{chosen.map((p,i)=><button className={`editorial-photo photo-${i}`} key={p.id} onClick={()=>setSelected({photos:a.photos,index:a.photos.findIndex(x=>x.id===p.id)})} aria-label={`Ampliar: ${p.caption}`}><img src={p.thumb} alt={p.caption} loading={n===0&&i===0?'eager':'lazy'}/><span className="image-expand"><ArrowUpRight size={21}/></span></button>)}</div><div className="story-caption"><span>{a.demo?'Seleção de exemplo · fotografias de autores do Unsplash':a.description}</span><span>{a.photos.length} fotografias</span></div></article>})}{!albums.length&&<p className="empty">Novas histórias estão a caminho.</p>}</section></main><SiteFooter name={profile.name}/><PhotoViewer {...selected} onClose={()=>setSelected({...selected,index:-1})} onIndex={index=>setSelected({...selected,index})}/><Motion/></>
}
export function Gallery({album,profile,preview=false}:{album:Album;profile:Profile;preview?:boolean}){const [index,setIndex]=useState(-1);return <><SiteHeader {...profile}/><main className="gallery-main">{preview&&<div className="notice">Prévia privada. Este trabalho ainda não está publicado.</div>}<a className="back-link" href="/"><ArrowLeft size={17}/> Todas as histórias</a><div className="gallery-title"><div className="eyebrow">{album.category}{album.demo&&<span className="demo-badge">Demonstração</span>}</div><h1>{album.title}</h1><p>{album.description}</p><Film album={album}/></div><div className="gallery-meta"><span>Um olhar mais de perto</span><span>{album.photos.length} fotografias · toque para ampliar</span></div><div className="masonry">{album.photos.map((p,i)=><button key={p.id} onClick={()=>setIndex(i)} aria-label={`Ampliar: ${p.caption}`}><img src={p.thumb} alt={p.caption} loading={i<3?'eager':'lazy'}/></button>)}</div>{album.demo&&<p className="demo-note">Galeria demonstrativa. Créditos de cada fotografia disponíveis ao ampliar a imagem.</p>}</main><SiteFooter name={profile.name}/><PhotoViewer photos={album.photos} index={index} onIndex={setIndex} onClose={()=>setIndex(-1)}/></>}
